--- 
pathToTemplateModelsDirectory: 
directoryToSaveModels:
directoryToInteraction:
directoryToExportModels: 
pathToProfile: 
pathToProfileConcern: 
pathToProfileRelationships: 
pathToProfilePatterns: 
