--- 
pathToTemplateModelsDirectory: 
directoryToSaveModels:
directoryToInteraction:
directoryToExportModels:
pathLastOptimizationInput:
pathToProfile: 
pathToProfileConcern: 
pathToProfileRelationships: 
pathToProfilePatterns: 
